rtas_dbg: address string format truncation warning
GCC 9.3.1 warns:

src/rtas_dbg.c: In function ‘get_rtas_tokens’:
src/rtas_dbg.c:137:26: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 105 [-Werror=format-truncation=]
  137 |   snprintf(dir, 128, "%s/%s", OFDT_RTAS_PATH, dp->d_name);
      |                          ^~
In file included from /usr/include/stdio.h:867,
                 from src/rtas_dbg.c:30:
/usr/include/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 24 and 279 bytes into a destination of size 128

The lazy but least risky change to make here is to simply enlarge the
(oddly named) on-stack buffer to accommodate the longest possible
result.

Signed-off-by: Nathan Lynch <nathanl@linux.ibm.com>
Signed-off-by: Tyrel Datwyler <tyreld@linux.ibm.com>