drmgr/common_ofdt: correct stringop-truncation warning
With -Wall -Werror GCC 9.3.1 emits:
In file included from /usr/include/string.h:495,
                 from src/drmgr/common_ofdt.c:24:
In function ‘strncpy’,
    inlined from ‘drc_info_connectors_v2’ at src/drmgr/common_ofdt.c:338:4,
    inlined from ‘get_drc_info’ at src/drmgr/common_ofdt.c:431:8:
/usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 48 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));

The GCC manual's documentation for -Wstringop-truncation suggests
correcting this case by specifying 'sizeof buf - 1' for the strncpy
bound and setting the last element of the buffer to 'NUL', which is
sufficient.

Signed-off-by: Nathan Lynch <nathanl@linux.ibm.com>
Signed-off-by: Tyrel Datwyler <tyreld@linux.ibm.com>