lsslot: Fix missing header for __be32 types
On my system (Ubuntu 15.04) lsslot does not build as it's missing the
__be32 types.

 src/drmgr/lsslot.c: In function ‘print_drconf_mem’:
 src/drmgr/lsslot.c:712:2: error: unknown type name ‘__be32’
   __be32 *aa;

Signed-off-by: Joel Stanley <joel@jms.id.au>