nvram.c: Correct librtas function prototypes
Fix build breakage with GCC 15 (which assumes C23) such that and empty
argument list is treated as zero arguments rather than an arbitrary
number.

src/nvram.c: In function ‘dump_rtas_event_entry’:
src/nvram.c:932:18: error: too many arguments to function ‘parse_rtas_event’; expected 0, have 2
  932 |     rtas_event = parse_rtas_event(data, len);
      |                  ^~~~~~~~~~~~~~~~ ~~~~
src/nvram.c:938:5: error: too many arguments to function ‘rtas_print_event’; expected 0, have 3
  938 |     rtas_print_event(stdout, rtas_event, 0);
      |     ^~~~~~~~~~~~~~~~ ~~~~~~
src/nvram.c:940:5: error: too many arguments to function ‘cleanup_rtas_event’; expected 0, have 1
  940 |     cleanup_rtas_event(rtas_event);
      |     ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~
In file included from src/vcpustat.c:34:

Signed-off-by: Michal Suchanek <msuchanek@suse.de>
[tyreld: add description to commit log]
Signed-off-by: Tyrel Datwyler <tyreld@linux.ibm.com>